print([' '])
print([' '])
print(['🙂'])
print(['◈'])
while input('Press W to jump. ').upper() != 'W':
    pass
print([' '])
print(['🙂'])
print([' '])
print(['◈'])
print()
print(['🙂'])
print([' '])
print([' '])
print(['◈'])
print()
print(['🙂'])
print([' '])
print([' '])
print(['◈'])
print()
print([' '])
print(['🙂'])
print([' '])
print(['◈'])
print()
print([' '])
print([' '])
print(['🙂'])
print(['◈'])
print('\n\nNote: You can\'t jump in midair')
print('\nTutorial Finished!')
